// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8miQweDLABQkUEt1lLN18aBXVwpbHciI',
    appId: '1:553286417167:web:737ddc6a496c0261f1dc7a',
    messagingSenderId: '553286417167',
    projectId: 'ecommerce-app-3e915',
    authDomain: 'ecommerce-app-3e915.firebaseapp.com',
    storageBucket: 'ecommerce-app-3e915.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqYvJmG-DnKmR3az7qSv7M2DKXYwsWWs',
    appId: '1:553286417167:android:d786e655d4a0a825f1dc7a',
    messagingSenderId: '553286417167',
    projectId: 'ecommerce-app-3e915',
    storageBucket: 'ecommerce-app-3e915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXV1n759iYP42NyVIgiUEIvGOEO7VuCDQ',
    appId: '1:553286417167:ios:5cbdaa727ddc87c7f1dc7a',
    messagingSenderId: '553286417167',
    projectId: 'ecommerce-app-3e915',
    storageBucket: 'ecommerce-app-3e915.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXV1n759iYP42NyVIgiUEIvGOEO7VuCDQ',
    appId: '1:553286417167:ios:5cbdaa727ddc87c7f1dc7a',
    messagingSenderId: '553286417167',
    projectId: 'ecommerce-app-3e915',
    storageBucket: 'ecommerce-app-3e915.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8miQweDLABQkUEt1lLN18aBXVwpbHciI',
    appId: '1:553286417167:web:3f3f4f3df0401f07f1dc7a',
    messagingSenderId: '553286417167',
    projectId: 'ecommerce-app-3e915',
    authDomain: 'ecommerce-app-3e915.firebaseapp.com',
    storageBucket: 'ecommerce-app-3e915.firebasestorage.app',
  );
}
